# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.manage_host = true
  config.hostmanager.enabled = true

  config.vm.define "vds" do |vds|
    vds.vm.box = "debian/jessie64"
    #vds.disksize.size = '20GB'
    vds.vm.network "private_network", ip: "192.168.90.123"
    vds.vm.hostname = "vds.verteego.local"
    vds.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
  end

end