---
- name: Add source.list file
  copy: src=webupd8team-java.list dest=/etc/apt/sources.list.d/webupd8team-java.list
  register: add_source_result
  become: yes

- name: Add apt-key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886
  become: yes

- name: Update apt cache
  apt: update_cache=yes
  when: add_source_result.changed == true
  become: yes